services:
  mc:
    image: energypatrikhu/pterodactyl-minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      MAX_MEMORY: 4G
      MODRINTH_PROJECTS: |
        luckperms
      APPLY_EXTRA_FILES: |
        plugins/LuckPerms</shared-configs/LuckPerms/
      DEBUG: true
    volumes:
      - data:/home/container
      - ./shared-configs:/shared-configs:ro
    ports:
      - "25565:25565"
volumes:
  data:
