services:
  mc:
    image: energypatrikhu/pterodactyl-minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: true
      TYPE: FABRIC
      MODRINTH_PROJECTS: |
        jline4mcdsrv
    volumes:
      - mc-data:/home/container
volumes:
  mc-data: {}
