services:
  minecraft:
    image: energypatrikhu/pterodactyl-minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./home/container:/home/container
    environment:
      EULA: "TRUE"
    restart: unless-stopped
