services:
  mc:
    image: energypatrikhu/pterodactyl-minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.7.2
      WORLD: https://www.minecraftmaps.com/survival-maps/cube-survival/download
