services:
  minecraft:
    image: energypatrikhu/pterodactyl-minecraft-server
    volumes:
      - ./home/container:/home/container
      - ./mods:/mods
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.19.2"
    tty: true
    stdin_open: true
