services:
  mc:
    image: energypatrikhu/pterodactyl-minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      MODRINTH_PROJECTS: fallingtree
    volumes:
      - data:/home/container

volumes:
  data: {}
