services:
  mc:
    image: energypatrikhu/pterodactyl-minecraft-server
    environment:
      EULA: true
      TYPE: NEOFORGE
      VERSION: latest
      NEOFORGE_VERSION: beta
    ports:
      - "25565:25565"
    volumes:
      - mc:/home/container
volumes:
  mc: {}
